//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftService.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int pos_id { get; set; }
        public string product_uid { get; set; }
        public int product_id { get; set; }
        public string pos_user_uid { get; set; }
        public string pay_system_uid { get; set; }
        public int pay_system_id { get; set; }
        public bool is_payment_processed { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> pay_system_response_at { get; set; }
    }
}
