//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. paštas.
        /// </summary>
        internal static string Auth_Login_Email {
            get {
                return ResourceManager.GetString("Auth_Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slaptažodis.
        /// </summary>
        internal static string Auth_Login_Password {
            get {
                return ResourceManager.GetString("Auth_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisijungti.
        /// </summary>
        internal static string Auth_Login_Submit {
            get {
                return ResourceManager.GetString("Auth_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite savo el.paštą ir slaptažodį.
        /// </summary>
        internal static string Auth_Login_Title {
            get {
                return ResourceManager.GetString("Auth_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingai uzpildyti dovanos laukai.
        /// </summary>
        internal static string Gift_EmailFriend_IncorrectParameters {
            get {
                return ResourceManager.GetString("Gift_EmailFriend_IncorrectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsisiusti PDF.
        /// </summary>
        internal static string Gift_Get_ButtonDownloadAsPdf {
            get {
                return ResourceManager.GetString("Gift_Get_ButtonDownloadAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Išsiųsti el.paštu.
        /// </summary>
        internal static string Gift_Get_ButtonSendAsEmail {
            get {
                return ResourceManager.GetString("Gift_Get_ButtonSendAsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dovanų čekis.
        /// </summary>
        internal static string Gift_Get_CouponByEmail {
            get {
                return ResourceManager.GetString("Gift_Get_CouponByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuponas galioja iki.
        /// </summary>
        internal static string Gift_Get_CouponIsValidTill {
            get {
                return ResourceManager.GetString("Gift_Get_CouponIsValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsisiųsti kuponą.
        /// </summary>
        internal static string Gift_Get_DownloadCoupon {
            get {
                return ResourceManager.GetString("Gift_Get_DownloadCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite svekinimą.
        /// </summary>
        internal static string Gift_Get_EnterCongratulations {
            get {
                return ResourceManager.GetString("Gift_Get_EnterCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siųsti dovanų čekį el. paštu:.
        /// </summary>
        internal static string Gift_Get_GiftEmailLabel {
            get {
                return ResourceManager.GetString("Gift_Get_GiftEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;non-attractive&quot;&gt;Aprašymas nenurodytas&lt;/span&gt;.
        /// </summary>
        internal static string Gift_Get_NoDescription {
            get {
                return ResourceManager.GetString("Gift_Get_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumokėta.
        /// </summary>
        internal static string Gift_Get_PaidAt {
            get {
                return ResourceManager.GetString("Gift_Get_PaidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmokėjimas vykdomas, prašome palaukti.
        /// </summary>
        internal static string Gift_Get_PaymentIsProcessing {
            get {
                return ResourceManager.GetString("Gift_Get_PaymentIsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmokėjimas nebuvo atliktas.
        /// </summary>
        internal static string Gift_Get_PaymentWasNot {
            get {
                return ResourceManager.GetString("Gift_Get_PaymentWasNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsispausdinti kuponą.
        /// </summary>
        internal static string Gift_Get_PrintCoupon {
            get {
                return ResourceManager.GetString("Gift_Get_PrintCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trukmė:.
        /// </summary>
        internal static string Gift_Get_ProductDurationLabel {
            get {
                return ResourceManager.GetString("Gift_Get_ProductDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenurodyta.
        /// </summary>
        internal static string Gift_Get_ProductDurationNotSet {
            get {
                return ResourceManager.GetString("Gift_Get_ProductDurationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paslauga:.
        /// </summary>
        internal static string Gift_Get_ServiceLabel {
            get {
                return ResourceManager.GetString("Gift_Get_ServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėkojame, kad naudojatės mūsų paslaugomis!.
        /// </summary>
        internal static string Gift_Get_ThankYouForUsingUs {
            get {
                return ResourceManager.GetString("Gift_Get_ThankYouForUsingUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privalote užsiregistruoti:.
        /// </summary>
        internal static string Gift_Get_YouMustReserve {
            get {
                return ResourceManager.GetString("Gift_Get_YouMustReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemos prezentacija.
        /// </summary>
        internal static string Home_AboutUs_Title {
            get {
                return ResourceManager.GetString("Home_AboutUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užduokite klausimą.
        /// </summary>
        internal static string Home_ContactUs_Ask {
            get {
                return ResourceManager.GetString("Home_ContactUs_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reikia pagalbos?.
        /// </summary>
        internal static string Home_ContactUs_DoYouNeedHelp {
            get {
                return ResourceManager.GetString("Home_ContactUs_DoYouNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų el. paštas.
        /// </summary>
        internal static string Home_ContactUs_Email {
            get {
                return ResourceManager.GetString("Home_ContactUs_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ačiū, Jūsų užklausa išsiųsta.
        /// </summary>
        internal static string Home_ContactUs_MessageIsSentOk {
            get {
                return ResourceManager.GetString("Home_ContactUs_MessageIsSentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų vardas.
        /// </summary>
        internal static string Home_ContactUs_Name {
            get {
                return ResourceManager.GetString("Home_ContactUs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siųsti.
        /// </summary>
        internal static string Home_ContactUs_Send {
            get {
                return ResourceManager.GetString("Home_ContactUs_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų svetainės adresas.
        /// </summary>
        internal static string Home_ContactUs_SiteUrl {
            get {
                return ResourceManager.GetString("Home_ContactUs_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Home_ContactUs_Subject {
            get {
                return ResourceManager.GetString("Home_ContactUs_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užklausa.
        /// </summary>
        internal static string Home_ContactUs_Text {
            get {
                return ResourceManager.GetString("Home_ContactUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktai.
        /// </summary>
        internal static string Home_ContactUs_Title {
            get {
                return ResourceManager.GetString("Home_ContactUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titullinis.
        /// </summary>
        internal static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupono įsigijimo taisyklės.
        /// </summary>
        internal static string Home_Rules_Title {
            get {
                return ResourceManager.GetString("Home_Rules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to būtinas.
        /// </summary>
        internal static string Label_RequiredMale {
            get {
                return ResourceManager.GetString("Label_RequiredMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apie mus.
        /// </summary>
        internal static string Menu_AboutUs {
            get {
                return ResourceManager.GetString("Menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktai.
        /// </summary>
        internal static string Menu_Contacts {
            get {
                return ResourceManager.GetString("Menu_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristatymas.
        /// </summary>
        internal static string Menu_Presentation {
            get {
                return ResourceManager.GetString("Menu_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taisyklės.
        /// </summary>
        internal static string Menu_Rules {
            get {
                return ResourceManager.GetString("Menu_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atgal į parduotuvę.
        /// </summary>
        internal static string Payment_Cancel_BackToProductPage {
            get {
                return ResourceManager.GetString("Payment_Cancel_BackToProductPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų mokėjimas atšauktas.
        /// </summary>
        internal static string Payment_Cancel_YouCancelledYourPayment {
            get {
                return ResourceManager.GetString("Payment_Cancel_YouCancelledYourPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite aptarnavimo vietą.
        /// </summary>
        internal static string Payment_Checkout_ChooseLocation {
            get {
                return ResourceManager.GetString("Payment_Checkout_ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuponas galioja iki.
        /// </summary>
        internal static string Payment_Checkout_CouponIsValidTill {
            get {
                return ResourceManager.GetString("Payment_Checkout_CouponIsValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. paštas.
        /// </summary>
        internal static string Payment_Checkout_CustomerEmail {
            get {
                return ResourceManager.GetString("Payment_Checkout_CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardas.
        /// </summary>
        internal static string Payment_Checkout_CustomerName {
            get {
                return ResourceManager.GetString("Payment_Checkout_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. nr..
        /// </summary>
        internal static string Payment_Checkout_CustomerPhone {
            get {
                return ResourceManager.GetString("Payment_Checkout_CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenurodyta.
        /// </summary>
        internal static string Payment_Checkout_DurationNotSet {
            get {
                return ResourceManager.GetString("Payment_Checkout_DurationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokėti.
        /// </summary>
        internal static string Payment_Checkout_PayButton {
            get {
                return ResourceManager.GetString("Payment_Checkout_PayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmokėjimas.
        /// </summary>
        internal static string Payment_Checkout_Payment {
            get {
                return ResourceManager.GetString("Payment_Checkout_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastabos.
        /// </summary>
        internal static string Payment_Checkout_Remarks {
            get {
                return ResourceManager.GetString("Payment_Checkout_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida vykdant apmokėjimą. Mūsų darbuotojai susisieks su Jumis..
        /// </summary>
        internal static string Payment_ErrorProcessingTransaction {
            get {
                return ResourceManager.GetString("Payment_ErrorProcessingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida apdorojant mokėjimo duomenis.
        /// </summary>
        internal static string Payment_Incorrect_ErrorMakingPayment {
            get {
                return ResourceManager.GetString("Payment_Incorrect_ErrorMakingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisinga prekės kaina, todėl pirkimo procesas sustabdytas.
        ///Susisiekite su administracija..
        /// </summary>
        internal static string Payment_Make_Error_IncorrectPriceFromRequest {
            get {
                return ResourceManager.GetString("Payment_Make_Error_IncorrectPriceFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveikiname, Jūs įsigijote kuponą..
        /// </summary>
        internal static string Payment_PaymentIsOk {
            get {
                return ResourceManager.GetString("Payment_PaymentIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šiuo metu klientai nerodomi.
        /// </summary>
        internal static string Pos_OurClients_NoResults {
            get {
                return ResourceManager.GetString("Pos_OurClients_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mūsų klientai.
        /// </summary>
        internal static string Pos_OurClients_Title {
            get {
                return ResourceManager.GetString("Pos_OurClients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsiprašome, vyksta techniniai darbai ir informacija nerasta..
        /// </summary>
        internal static string SystemMessage_NotFound {
            get {
                return ResourceManager.GetString("SystemMessage_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mūsų darbuotojai su Jumis susisieks..
        /// </summary>
        internal static string SystemMessage_WeWillContactYouOnError {
            get {
                return ResourceManager.GetString("SystemMessage_WeWillContactYouOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikrinti.
        /// </summary>
        internal static string TranAdmin_Validate_ButtonCheck {
            get {
                return ResourceManager.GetString("TranAdmin_Validate_ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite kupono unikalų kodą arba numerį.
        /// </summary>
        internal static string TranAdmin_Validate_EnterTransactionCode {
            get {
                return ResourceManager.GetString("TranAdmin_Validate_EnterTransactionCode", resourceCulture);
            }
        }
    }
}
