//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuponas galioja iki.
        /// </summary>
        internal static string Gift_Get_CouponIsValidTill {
            get {
                return ResourceManager.GetString("Gift_Get_CouponIsValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsisiųsti kuponą.
        /// </summary>
        internal static string Gift_Get_DownloadCoupon {
            get {
                return ResourceManager.GetString("Gift_Get_DownloadCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumokėta.
        /// </summary>
        internal static string Gift_Get_PaidAt {
            get {
                return ResourceManager.GetString("Gift_Get_PaidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmokėjimas vykdomas, prašome palaukti.
        /// </summary>
        internal static string Gift_Get_PaymentIsProcessing {
            get {
                return ResourceManager.GetString("Gift_Get_PaymentIsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmokėjimas nebuvo atliktas.
        /// </summary>
        internal static string Gift_Get_PaymentWasNot {
            get {
                return ResourceManager.GetString("Gift_Get_PaymentWasNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsispausdinti kuponą.
        /// </summary>
        internal static string Gift_Get_PrintCoupon {
            get {
                return ResourceManager.GetString("Gift_Get_PrintCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paslauga:.
        /// </summary>
        internal static string Gift_Get_ServiceLabel {
            get {
                return ResourceManager.GetString("Gift_Get_ServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėkojame, kad naudojatės mūsų paslaugomis!.
        /// </summary>
        internal static string Gift_Get_ThankYouForUsingUs {
            get {
                return ResourceManager.GetString("Gift_Get_ThankYouForUsingUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privalote užsiregistruoti:.
        /// </summary>
        internal static string Gift_Get_YouMustReserve {
            get {
                return ResourceManager.GetString("Gift_Get_YouMustReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemos prezentacija.
        /// </summary>
        internal static string Home_AboutUs_Title {
            get {
                return ResourceManager.GetString("Home_AboutUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aciū, Jūsų užklausa išsiusta.
        /// </summary>
        internal static string Home_ContactUs_MessageIsSentOk {
            get {
                return ResourceManager.GetString("Home_ContactUs_MessageIsSentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atgal į parduotuvę.
        /// </summary>
        internal static string Payment_Cancel_BackToProductPage {
            get {
                return ResourceManager.GetString("Payment_Cancel_BackToProductPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų mokėjimas atšauktas.
        /// </summary>
        internal static string Payment_Cancel_YouCancelledYourPayment {
            get {
                return ResourceManager.GetString("Payment_Cancel_YouCancelledYourPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite aptarnavimo vietą.
        /// </summary>
        internal static string Payment_Checkout_ChooseLocation {
            get {
                return ResourceManager.GetString("Payment_Checkout_ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenurodyta.
        /// </summary>
        internal static string Payment_Checkout_DurationNotSet {
            get {
                return ResourceManager.GetString("Payment_Checkout_DurationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida vykdant apmokėjimą. Mūsų darbuotojai susisieks su Jumis..
        /// </summary>
        internal static string Payment_ErrorProcessingTransaction {
            get {
                return ResourceManager.GetString("Payment_ErrorProcessingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida apdorojant mokėjimo duomenis.
        /// </summary>
        internal static string Payment_Incorrect_ErrorMakingPayment {
            get {
                return ResourceManager.GetString("Payment_Incorrect_ErrorMakingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisinga prekės kaina, todėl pirkimo procesas sustabdytas.
        ///Susisiekite su administracija..
        /// </summary>
        internal static string Payment_Make_Error_IncorrectPriceFromRequest {
            get {
                return ResourceManager.GetString("Payment_Make_Error_IncorrectPriceFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveikiname, Jūs įsigijote kuponą..
        /// </summary>
        internal static string Payment_PaymentIsOk {
            get {
                return ResourceManager.GetString("Payment_PaymentIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siuo metu klientai nerodomi.
        /// </summary>
        internal static string Pos_OurClients_NoResults {
            get {
                return ResourceManager.GetString("Pos_OurClients_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mūsų klientai.
        /// </summary>
        internal static string Pos_OurClients_Title {
            get {
                return ResourceManager.GetString("Pos_OurClients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsiprašome, vyksta techniniai darbai ir informaciją nerasta..
        /// </summary>
        internal static string SystemMessage_NotFound {
            get {
                return ResourceManager.GetString("SystemMessage_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mūsų darbuotojai su Jumis susisieks..
        /// </summary>
        internal static string SystemMessage_WeWillContactYouOnError {
            get {
                return ResourceManager.GetString("SystemMessage_WeWillContactYouOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikrinti.
        /// </summary>
        internal static string TranAdmin_Validate_ButtonCheck {
            get {
                return ResourceManager.GetString("TranAdmin_Validate_ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iveskite kupono unikalu koda arba numeri.
        /// </summary>
        internal static string TranAdmin_Validate_EnterTransactionCode {
            get {
                return ResourceManager.GetString("TranAdmin_Validate_EnterTransactionCode", resourceCulture);
            }
        }
    }
}
